[package]
name = "ntcore-sys"
authors = ["Gavin Niederman <gavinniederman@gmail.com>"]
description = "Raw Rust bindings to ntcore"
keywords = ["ntcore", "networktables", "frc", "wpilib"]
categories = ["api-bindings", "external-ffi-bindings", "network-programming"]
repository = "https://github.com/gavin-niederman/lagan"
license = "MIT"
version = "0.2.0"
edition = "2021"

[build-dependencies]
cmake = "0.1"

[dependencies]
bitflags = "2.6.0"
