[package]
name = "lagan-gui"
authors = ["Gavin Niederman <gavinniederman@gmail.com>"]
description = "A NetworkTables explorer similar to glass"
keywords = ["ntcore", "networktables", "frc", "wpilib"]
categories = ["api-bindings", "external-ffi-bindings", "network-programming"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.6", default-features = false, features = ["macro", "hooks"] }
freya = { git = "https://github.com/marc2332/freya" }
lagan = { path = "../lagan", version = "0.1.0" }
