[package]
name = "lagan"
authors = ["Gavin Niederman <gavinniederman@gmail.com>"]
description = "Safe bindings for ntcore"
keywords = ["ntcore", "networktables", "frc", "wpilib"]
categories = ["api-bindings", "external-ffi-bindings", "network-programming"]
license = "MIT"
readme = "../../README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
libntcore = { path = "../libntcore", version = "0.1.0" }
typed-builder = "0.20.0"
